CREATE TABLE TBL_CONSUMO (
     id NUMBER PRIMARY KEY,
     equipamento VARCHAR2(255 CHAR) NOT NULL,
     consumo_kwh NUMBER(10,2) NOT NULL,
     data_leitura DATE NOT NULL
);

CREATE SEQUENCE CONSUMO_SEQ START WITH 1 INCREMENT BY 1;
